# ARRAY CREATION
### array()

array() is the main function of NumPy, which converts a list or tuple into a NumPy array.

An array is a multidimensional container that allows you to store and operate on numbers efficiently.


In [8]:
import numpy as np
a=np.array([1,2,3,4]) #1d array
print(a)

b=np.array([[1,2],[2,4]])
print(b)

[1 2 3 4]
[[1 2]
 [2 4]]


### shape()
shape tells the dimensions of the array.

For 2D arrays, it is given as a tuple (rows, columns)

In [9]:
print(a.shape)
print(b.shape)

(4,)
(2, 2)


### reshape()

reshape() allows you to change the size or dimensions of an array without changing its elements.

The total number of elements must remain the same.

In [16]:
c=np.array([1,2,3,4,4,3])
c2=c.reshape(2,3)
print(c2)

[[1 2 3]
 [4 4 3]]


### Basic Operations: + , - , * , /

With NumPy arrays, mathematical operations are element-wise.

That means the operation is applied to each element individually.

In [23]:
x=np.array([7,4,3,2,2])
y=np.array([6,8,4,4,3])
z=x+y
print(z)
print(x*y)
print(x/y)
print(x-y)

[13 12  7  6  5]
[42 32 12  8  6]
[1.16666667 0.5        0.75       0.5        0.66666667]
[ 1 -4 -1 -2 -1]


### Statistical Operations: mean(), max(), min()

mean() → Calculates the average of array elements

max() → Finds the largest element

min() → Finds the smallest element

In [28]:
print(x.mean())
print(x.max())
print(x.min())
print(b.mean(axis=0))  # Column-wise mean
print(b.mean(axis=1))  # Row-wise mean 



3.6
7
2
[1.5 3. ]
[1.5 3. ]
